spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://b7gly0oyfylhymgzzvae-mysql.services.clever-cloud.com:3306/b7gly0oyfylhymgzzvae}
    username: ${JDBC_DATABASE_USERNAME:upoztd88l50x7tbu}
    password: ${JDBC_DATABASE_PASSWORD:Elder2316394}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
logging:
  level:
    com.cstv.cstv: DEBUG